### PR TITLE
Android Firebase + Firebase Crashlytics Integration

### PR DESCRIPTION
**Pull request by innovation-elab**
Android Integration OK and tested.
For IOS following steps still need to be done and then tested:
https://firebase.google.com/docs/crashlytics/get-started?platform=ios#add-sdk

### CODE REVIEW

**Comment by tborlee** [comment]
google-services.json should not be committed in the open source repository I think, but rather in the private asset ones.

Also, we should update README accordingly to specify that and to explain how to integrate the Firebase config file.

It would be better also to have one Firebase config file for DEBUG and one for RELEASE, so that we never by mistake send test messages on production for example.

**Comment by innovation-elab** [comment]
> google-services.json should not be committed in the open source repository I think, but rather in the private asset ones.

Apparently it's safe to check in to your repo, from this => https://groups.google.com/g/firebase-talk/c/bamCgTDajkw/m/uVEJXjtiBwAJ

> It would be better also to have one Firebase config file for DEBUG and one for RELEASE, so that we never by mistake send test messages on production for example.

Indeed, I'll rework the code as to make this work.

**Comment by tborlee** [comment]
> Apparently it's safe to check in to your repo, from this => https://groups.google.com/g/firebase-talk/c/bamCgTDajkw/m/uVEJXjtiBwAJ

Yes it is safe, but since it's an open source project, I don't think we should keep the file here as it is directly linked to  the Adep's version on  the store.

If someone checks out the project and want to test or release a different version , this file is no use for him and he will need to replace it in all cases

**Comment by innovation-elab** [comment]
> Yes it is safe, but since it's an open source project, I don't think we should keep the file here as it is directly linked to the Adep's version on the store.
If someone checks out the project and want to test or release a different version , this file is no use for him and he will need to replace it in all cases

I've tested without the file, and it works, because the configuration file 'firebase_options' doesn't use the google-json.services file. But you're right, I'll remove the firebase_options file then from git and will add comments to readme...

**Comment by tborlee** [comment]
Just saw that flutter 3 was released today, and fire add integration has been improved a lot.

I suggest that the next release contains only bug fixes, and release firebase integration later with Flutter 3 migration

**Pull request closed without merging**
