### PR TITLE
App refactoring (Layout, Navigation, BackgroundFetch, Singletons etc...)

### PR DESCRIPTION
**Pull request by innovation-elab**
Did a little side project and tried some stuff to learn flutter a little more in depth.
Doesn't need to go in production, but if it's sufficiently good and tested it's an option...

- Still needs work on the 'Annuaire' page which is probably not stable.
- Needs Firebase Integration (Crashlytics + in_app_messaging)
- Doesn't have the 'news'-widget that is in master
- Needs to be tested thoroughly (should write code tests ideally)
- Still needs responsive-layout integration for Ipads

### CODE REVIEW

**Comment by tborlee** [comment]
I like the new loading screen (spinner with the logo above) and how we can sort and filter the list.

Not a fan of the navigation drawer - new Material specification tries to avoid them, and we have only 3 items, so fells very empty. I think the navigation bar at the bottom is a better approach.

For the walk tiles, it looks a bit empty now without the logo, and the title/descriptions/chips are too close together.

For settings, Home location should not be related to notification I think - user could define it just to have the list sorted, without notifications enabled.

**Comment by innovation-elab** [comment]
> Not a fan of the navigation drawer - new Material specification tries to avoid them, and we have only 3 items, so fells very empty. I think the navigation bar at the bottom is a better approach.

I'll try again with the bottom navigation bar, you are correct that it is empty. I tried this because I though maybe we could add the settings inside the drawer but that was a bad idea.

> For the walk tiles, it looks a bit empty now without the logo, and the title/descriptions/chips are too close together.
I agree, I'll rework this. I tried removing unuseful information, but I think it's better with the logo...

> For settings, Home location should not be related to notification I think - user could define it just to have the list sorted, without notifications enabled.

When a user tries to sort by 'home' and he doesn't have a 'home' selected, he will be able to add his address as well. But you're right that it doesn't really belong to notifications only, I'll try and rethink how to do it. I just thought it looked nicer that way, but I agree it's not 100% clear.

**Comment by tborlee** [comment]
> I agree, I'll rework this. I tried removing unuseful information, but I think it's better with the logo...
I agree that the logo doesn't bring anything useful. Maybe show a map static map there of the place instead?

> I just thought it looked nicer that way, but I agree it's not 100% clear.
It looks definitively better and cleaner yes, but sadly for me we should separate them as they serve different purposes

**Comment by innovation-elab** [comment]
> I agree that the logo doesn't bring anything useful. Maybe show a map static map there of the place instead?

I'll try. Of course some actual pictures of the walk would be nice, but until then we'll work with the static map...

**Pull request closed without merging**
