### PR TITLE
Add GoogleMaps as Map-Service

### PR DESCRIPTION
**Pull request by sofyanbokornaetnic**
Start the development of #26

### CODE REVIEW

**Comment by tborlee** [comment]
Is this ready to review? If so, might need to resolve conflicts. If not, maybe put it in "draft" mode to keep it clear? Thanks

**Comment by sofyanbokornaetnic** [comment]
I spoke with Matthieu last week and we found potential improvements. I will focus on this on the following days and try to have a "ready to review" version by the end of the week.

**Comment by tborlee** [comment]
@sofyanbokornaetnic your PR has conflicts, can you resolve them? Thanks

**Comment by sofyanbokornaetnic** [comment]
I fixed the conflicts but I haven't tested it yet due to local errors with missing assets

**Comment by tborlee** [comment]
Did you generated the splash screens with `flutter pub run flutter_native_splash:create` (see readme)?

**Comment by sofyanbokornaetnic** [comment]
I did generated the splash screens and tested it locally. The only issue I found (and I am not sure that it is due to my changes), is that the first screen with the logo is not rendered the right way
wrong_logoPNG
.

**Comment by tborlee** [comment]
That's strange indeed, nothing seems correct on that screenshot. Are the resources generated by the tool correct?

**Comment by tborlee** [comment]
Didn’t realise it was the logo used as splash screen, normally there is a « card » image for that purpose.

**Comment by innovation-elab** [comment]
I remember you said the IOS default splash screen was going to use the logo. So I went ahead and used the logo as splash resource in assets. Should we revert back to the initial splash screen or do we go ahead and use the logo as splash screen and update the dimensions of the automatically created splash images?

**Comment by tborlee** [comment]
No I think you misunderstood:

- iOS will use the "card" image all the time.
- Android will use the "card" image on Android 11 and lower, and Android 12 will use the logo

So the pictures should be the same in the same files as before, no changes there.

**Comment by innovation-elab** [comment]
Ah ok, I'll generate the splash with the correct assets then.

**Comment by tborlee** [comment]
I will review this Pr this week-end.

**Review by innovation-elab — COMMENTED** [review]
Review changes on the Google Map service, Abstraction of the cache_managers, Added Map service instantiation based on environment, Updated 'About'-page with correct Map service, Updated ReadMe

**Pull request merged**
