### PR TITLE
Upgraded to Flutter 3.3 + Android 13 support + packages upgrade

### PR DESCRIPTION
**Pull request by tborlee**
- Upgraded to Flutter 3.3
- Upgraded all packages to latest version
- Android 13 support - SDK 33 + asking permission for notifications
- Removed unused packages (`package_info` and `carousel_slider`)

### CODE REVIEW

**Comment by innovation-elab** [comment]
Could you do following on a mac (i don't have access right now):

```
flutter clean
delete /ios/Pods
delete /ios/Podfile.lock
flutter pub get
from inside ios folder: pod install
```

And push after that. This should resolve the build error.

**Comment by tborlee** [comment]
I should be able to do the Mac part tonight after work, don't worry!

**Comment by tborlee** [comment]
@innovation-elab ios changes have been added

**Comment by tborlee** [comment]
Updated dependencies to be more up to date, but iOS build seems to crash now, will need to investigate further.

**Comment by tborlee** [comment]
iOS crashes were due to a config issue on my side. Working properly now.

**Pull request merged**
